// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.mycompany.jsf;

import com.mycompany.jsf.AvisoBean;
import java.io.Serializable;

privileged aspect AvisoBean_Roo_Serializable {
    
    declare parents: AvisoBean implements Serializable;
    
    private static final long AvisoBean.serialVersionUID = 1L;
    
}
