// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.mycompany.jsf;

import com.mycompany.jsf.BeanPublicacion;

privileged aspect BeanPublicacion_Roo_Serializable {
    
    private static final long BeanPublicacion.serialVersionUID = 1L;
    
}
