// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.mycompany.jsf;

import com.mycompany.jsf.BloguerBean;
import java.io.Serializable;

privileged aspect BloguerBean_Roo_Serializable {
    
    declare parents: BloguerBean implements Serializable;
    
    private static final long BloguerBean.serialVersionUID = 1L;
    
}
