// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.mycompany.jsf;

import com.mycompany.jsf.BloguerBean;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect BloguerBean_Roo_Configurable {
    
    declare @type: BloguerBean: @Configurable;
    
}
