// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.mycompany.jsf;

import com.mycompany.jsf.CategoriaBean;
import java.io.Serializable;

privileged aspect CategoriaBean_Roo_Serializable {
    
    declare parents: CategoriaBean implements Serializable;
    
    private static final long CategoriaBean.serialVersionUID = 1L;
    
}
