// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.mycompany.jsf;

import com.mycompany.jsf.TipoPersonaBean;
import java.io.Serializable;

privileged aspect TipoPersonaBean_Roo_Serializable {
    
    declare parents: TipoPersonaBean implements Serializable;
    
    private static final long TipoPersonaBean.serialVersionUID = 1L;
    
}
