// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.mycompany.jsf;

import com.mycompany.jsf.TipoDocumentoBean;
import java.io.Serializable;

privileged aspect TipoDocumentoBean_Roo_Serializable {
    
    declare parents: TipoDocumentoBean implements Serializable;
    
    private static final long TipoDocumentoBean.serialVersionUID = 1L;
    
}
