// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.mycompany.jsf;

import com.mycompany.jsf.TransaccionBean;
import java.io.Serializable;

privileged aspect TransaccionBean_Roo_Serializable {
    
    declare parents: TransaccionBean implements Serializable;
    
    private static final long TransaccionBean.serialVersionUID = 1L;
    
}
