// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.mycompany.jsf;

import com.mycompany.jsf.UsuarioBean;
import java.io.Serializable;

privileged aspect UsuarioBean_Roo_Serializable {
    
    declare parents: UsuarioBean implements Serializable;
    
    private static final long UsuarioBean.serialVersionUID = 1L;
    
}
