// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.mycompany.jsf;

import com.mycompany.jsf.VisitaBean;
import java.io.Serializable;

privileged aspect VisitaBean_Roo_Serializable {
    
    declare parents: VisitaBean implements Serializable;
    
    private static final long VisitaBean.serialVersionUID = 1L;
    
}
