// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.mycompany.jsf.converter;

import com.mycompany.jsf.converter.PublicacionConverter;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect PublicacionConverter_Roo_Configurable {
    
    declare @type: PublicacionConverter: @Configurable;
    
}
